# Generated by Django 3.2.6 on 2021-08-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(blank=True, choices=[('speaker', 'speaker'), ('participant', 'participant')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Duration_talk', models.DurationField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.conference')),
                ('public', models.ManyToManyField(blank=True, null=True, to='management.People')),
            ],
        ),
    ]
